theme: jekyll-theme-minimal
title: Home page of Vincent K.M. Cheung
name: Vincent K.M. Cheung
description: neuroscientist-in-training
markdown: kramdown

author:
  name: Vincent K.M. Cheung
  github: vkmcheung

  
